version: '2.1'
services:
  nginx:
    image: nginx:latest
    container_name: cdc-web
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static:/static
    depends_on:
      - app

  app:
    build: .
    container_name: cdc-app
    command: bash -c "./deploy.sh"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/src
      - static:/static
    env_file:
      - .env
    expose:
      - "8000"

  db:
    image: postgres:9.4
    container_name: cdc-db
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    # env_file:
    #   - .env

volumes:
  static:
