db:
  restart: always
  image: postgres:9.4
  ports:
    - "5432:5432"
  env_file:
    - .env

app:
  restart: always
  build: .
  env_file:
    - .env
  expose:
    - "8080"
  volumes:
    - ./coderdojochi:/src/coderdojochi
  links:
    - db

nginx:
  restart: always
  build: coderdojochi/static/
  ports:
    - "80:80"
  links:
    - app
