[tool]
[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
#default_section = "THIRDPARTY"
#known_first_party = []
#known_third_party = []
skip=['.eggs', '.git', '.hg', '.mypy_cache', '.nox', '.pants.d', '.tox', '.venv', '_build', 'buck-out', 'build', 'dist', 'node_modules', 'venv', 'migrations']

[tool.black]
line-length = 120
#target-version = ['py38']
#include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/

)
'''

[tool.poetry]
name = "we-all-code"
description = ""
version = "0.0.0"
license = "MIT"
readme = "README.md"
repository = "https://github.com/weallcode/website"
homepage = "https://github.com/weallcode/website"
authors = ["Ali Karbassi <ali@weallcode.org>"]

[tool.poetry.dependencies]
python = "==3.9.1"
arrow = "*"
boto3 = "*"
django = "*"
django-allauth = "*"
django-anymail = "*"
django-appconf = "*"
django-bootstrap3 = "*"
django-cleanup = "*"
django-common-helpers = "*"
django-cron = "*"
django-debug-toolbar = "*"
django-environ = "*"
django-fullurl = "*"
django-heroku = "*"
django-html5 = "*"
django-import-export = "*"
django-loginas = "*"
django-meta = "*"
django-nose = "*"
django-recaptcha = "*"
django-stdimage = "*"
django-storages = "*"
factory-boy = "*"
gunicorn = "*"
icalendar = "*"
invoke = "*"
json-logging-py = "*"
mock = "*"
pillow = "*"
psycopg2-binary = "*"
sentry-sdk = "*"
