app:
  build: ../..
  dockerfile: resources/docker/Dockerfile
  expose:
    - "8080"
  volumes:
    - /build/static
    - ../js/build/gulp:/build/gulp
    - ../..:/usr/src/app

nginx:
  image: nginx
  ports:
    - "80:80"
  links:
    - app
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  volumes_from:
    - app
