# name: Format

# on: [pull_request]

# jobs:
#   format:
#     name: Check format

#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 4

#     steps:
#       - uses: actions/checkout@v1

#       - name: Check format
#         uses: lgeiger/black-action@v1.0.1
#         with:
#           args: "."

#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: Apply black format changes

name: Format
on: [push, pull_request]
jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
